"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigImageStory2 from "@/components/sections/big-img-story-2";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";

export default function BlueprintPage() {
    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-black">
                <HeroTitle
                    title="BLUEPRINT"
                    subtitle="Services To Empower Your Success"
                    desktopImgUrl="/img/products/blueprintproduct.png"
                    mobileImgUrl="/img/products/mobile/blueprintproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[210px]">
                <BigTitleStory
                        title={`Success in real estate requires more than just luck and hard work`}
                        titleLeft={`Services`}
                        textLeft={`1. WEBFLOW DEVELOPMENT
                            2. APP INTEGRATION`}
                        titleRight={`About`}
                        textRight="Blueprint Capital provides construction financing to small-scale builders and develops income producing property for long-term value. As part of a new marketing initiative, Blueprint came to us looking for a development partner to rebuild their website."
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-video"
                        imgUrl={`/img/products/blueprint/blueprint-1.png`}
                        width={`90%`}
                        height={`60%`}
                        title={`Challenge`}
                        story={`Using the designs provided by their marketing team in Figma, we started the building process in Webflow. This was their preferred platform to easily manage the site within the designer view and native CMS.`}
                    />
                </div>

                <div className="  bg-[url(/img/products/blueprint/blueprint-2-bg.png)] bg-cover bg-center bg-no-repeat overflow-hidden">
                    <BigImageStory2
                        imgUrl={`/img/products/blueprint/blueprint-2.png`}
                        imageClassname="rounded-[8px]"
                        imageContainerClassname="aspect-[13/8] m-auto max-w-[1040px]"
                    />
                    <BigImageStory2                         textContainerClassname="px-[9px] lg:px-[19px]"

                        title={`Approach`}
                        story={`The second phase of development required us to rebuild a new Home Search experience, while still utilizing their current backend to manage property listings.`}
                        textColor={`text-white`}
                    />
                </div>
                <div className="rounded-[20px] mt-[120px] lg:mt-[200px] p-5 lg:p-10 ">
                    <BigImageOnly
                        imgUrl={`/img/products/blueprint/blueprint-3.png`}
                        className="aspect-[990/612] max-w-[990px] m-auto"
                        />
                </div>
                <div className="rounded-[20px] mt-[120px] lg:mt-[200px] p-5 lg:p-10 ">
                    <BigImageOnly
                        imgUrl={`/img/products/blueprint/blueprint-4.png`}
                        />
                </div>
            </div>
        </>
    );
}
