"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigImageStory2 from "@/components/sections/big-img-story-2";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";

export default function CertortPage() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative bg-black">
        <HeroTitle
          title="CERTOR"
          subtitle="Here to contend"
          desktopImgUrl="/img/products/certorproduct.png"
          mobileImgUrl="/img/products/mobile/certorproduct-mobile.png"
        />
        <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono]">
          <BigTitleStory
            title={`We’re leaders in technology, innovation, design, and sport`}
            titleLeft={`Schutt`}
            textRight="Certor Sports offers high-quality sports equipment with a focus on improving athletes' performance and safety. We helped develop Certor’s company website in Webflow, expanding off of the identity and UI work created by MUTO."
          />

          <BigImageStory
            imageContainerClassname="aspect-square md:aspect-video"
            imgUrl={`/img/products/certor/certor-1.png`}
            width={`90%`}
            height={`60%`}
          />
        </div>
        <div className="">
          <BigImageStory2
            imgUrl={`/img/products/certor/certor-2.png`}
            imageContainerClassname="aspect-[15/17] max-w-[1196px] m-auto"
            title={`Schutt`}
            story={`One main purpose of the site was to showcase job opportunities and attract potential employees. We developed a custom integration of their current hiring platform that was required to display current openings.`}
            textColor={`text-white`}
          />
        </div>

        <div className="rounded-[20px] overflow-hidden mb-[60px] lg:mb-[120px] bg-[#FDFCF3] py-[50px] px-[60px]">
          <BigImageOnly imgUrl={`/img/products/certor/certor-3.png`} />
        </div>
        <div className="rounded-[20px] overflow-hidden">
          <BigImageOnly imgUrl={`/img/products/certor/certor-4.png`} />
        </div>
      </div>
    </>
  );
}
