"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageSliderStory from "@/components/sections/big-img-slider-story";
import BigImageStory from "@/components/sections/big-img-story";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import { projectsData } from "../../sections/projectdata";

// Main component
export default function TDEApparel() {
    // Find the project with title "TDE"
    const project = projectsData.find((project) => project.title === "TDE");

    // Check if project is found, otherwise show fallback (to prevent undefined errors)
    if (!project) {
        return <div>Project data not found.</div>;
    }

    return (
        <>
            <Head>
                <title>{project.title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title={project.title} // Dynamically set the title
                    subtitle="Top Dawg Entertainment"
                    year={project.year} // Dynamically set the year
                    desktopImgUrl={project.image}
                    mobileImgUrl="/img/products/mobile/tdeproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[120px]">
                    <BigTitleStory
                        title={`The house that kendrick    built`}
                        titleLeft={`Sevices`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter((service) => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="Top Dawg Entertainment (TDE) is a renowned independent record label known for launching the careers of major artists like Kendrick Lamar, SZA, and Schoolboy Q. Celebrating their 20th anniversary, they approached us to modernize their eCommerce experience."
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-[1410/940]"
                        imgUrl={`/img/products/tde/tde-1.png`}
                        width={`90%`}
                        height={`60%`}
                        title={`Challenge`}
                        story={`Facing a tight deadline per usual, we jumped right into the design phase, working closely with the team to finalize decisions quickly before moving on to theme development. This gave us additional time to thoroughly QA the site before the official launch.`}
                    />
                </div>
                <div className="bg-[#D6D8CE] rounded-[20px]  pb-[80px]">
                    <BigImageStory
                        textContainerClassname="px-[9px] lg:px-[19px]"
                        imgUrl={`/img/products/tde/tde-2.png`}
                        imageContainerClassname="aspect-[1601/1715] max-w-[1601px] m-auto"
                        title={`Output`}
                        story={`Within 24 hours of the new site's launch, we boosted sales by four times through our custom performance-optimized Shopify theme and an impactful Klayvio campaign, which now serves as a template for future marketing efforts.`}
                    />
                </div>
                <div className="bg-[#1F1F1F] rounded-[20px]">
           
                    <BigImageSliderStory
                        imageContainerClassname="aspect-[1025/581] m-auto max-w-[1440px]"
                        images={[
                            "/img/products/tde/tde-3.png",
                            "/img/products/tde/tde-3.2.png",
                            "/img/products/tde/tde-3.3.png",
                        ]}
                        imageClassname="object-contain"
                    />
                </div>

                <div className="rounded-[20px] overflow-hidden">
                    <BigImageOnly imgUrl={`/img/products/tde/tde-4.png`} />
                </div>
            </div>
        </>
    );
}
