"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import { projectsData } from "../../sections/projectdata";

// Main component
export default function TDEApparel() {
    // Find the project with title "TDE"
    const project = projectsData.find((project) => project.title === "TDE");

    // Check if project is found, otherwise show fallback (to prevent undefined errors)
    if (!project) {
        return <div>Project data not found.</div>;
    }

    return (
        <>
            <Head>
                <title>{project.title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title={project.title} // Dynamically set the title
                    subtitle="Top Dawg Entertainment"
                    year={project.year} // Dynamically set the year
                    desktopImgUrl={project.image}
                    mobileImgUrl="/img/products/mobile/tdeproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[210px]">
                    <BigTitleStory
                        title={`We’re leaders in 
                            technology, innovation 
                            design,  and sport`}
                        titleLeft={`Services`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter(service => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="One main purpose of the site was to showcase job opportunities and attract potential employees. We developed a custom integration of their current hiring platform that was required to display current openings."
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-[1410/940]"
                        imgUrl={`/img/products/tde/tde-1.png`}
                        width={`90%`}
                        height={`60%`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands.`}
                    />
                </div>
                <div className="bg-[#D6D8CE] rounded-[20px]  pb-[80px]">
                    <BigImageStory
                        textContainerClassname="px-[9px] lg:px-[19px]"
                        imgUrl={`/img/products/tde/tde-2.png`}
                        imageContainerClassname="aspect-[1601/1715] max-w-[1601px] m-auto"
                        title={`Challenge`}
                        story={`One main purpose of the site was to showcase job opportunities and attract potential employees. We developed a custom integration of their current hiring platform that was required to display current openings.`}
                        textColor="text-black"
                    />
                </div>
                <div className="bg-[#1F1F1F] rounded-[20px]">
                    <BigImageStory
                        imageContainerClassname="aspect-[1025/581] m-auto max-w-[1025px]"
                        imgUrl={`/img/products/tde/tde-3.png`}
                    />
                </div>

                <div className="rounded-[20px] overflow-hidden">
                    <BigImageOnly imgUrl={`/img/products/tde/tde-4.png`} />
                </div>
            </div>
        </>
    );
}
