"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import { projectsData } from "../../sections/projectdata";

export default function TryitPage() {
    const project = projectsData.find((project) => project.title === "Tryit");

     if (!project) {
         return <div>Project data not found.</div>;
     }
    
    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title="Try It"
                    subtitle="Stick To The Plan"
                    desktopImgUrl="/img/products/tryitproduct.png"
                    mobileImgUrl="/img/products/mobile/tryitproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[210px]">
                <BigTitleStory
                        title={`Fun project where I can    share my design process and release random           products`}
                        titleLeft={`Services`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter(service => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="Try It Studios is a design studio situated in Los   Angeles. They curate unique partnerships with up-and-coming brands and special events, infusing their collection with an exclusive and varied appeal."
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-video"
                        imgUrl={`/img/products/tryit/tryit-1.png`}
                     
                        title={`Challenge`}
                        story={`Having collaborated on a previous eCommerce project, we approached them about revamping their site and creating a new custom theme for their Shopify store. `}
                    />
                </div>

                <div className="mb-[40px] lg:mb-[169px]">
                    <BigImageStory
                        imgUrl={`/img/products/tryit/tryit-2.png`}
                        imageContainerClassname="aspect-[39/49] m-auto max-w-[1572px]"
                        title={`Challenge`}
                        story={`As they were gearing up to unveil a new collection for the upcoming season, they saw the opportunity to synchronize the launch with a fresh new website. Despite a tight timeline, we wasted no time on the project and immediately initiated the process.`}
                        textColor={`text-white`}
                        textContainerClassname="px-[9px] lg:px-[19px]"
                    />
                </div>
                <div className="bg-[#FDFCF3] rounded-[20px] px-[9px] lg:px-[19px] pb-[40px] lg:pb-[169px]">
                    <BigImageStory
                        imgUrl={`/img/products/tryit/tryit-3.png`}
                        imageContainerClassname="aspect-[82/47] m-auto max-w-[1304px]"
                        title={`Challenge`}
                        textContainerClassname=""
                        story={`Their trust in our design approach was evident as we created a new UI style guide with minimal revisions. The process flowed smoothly, enabling us to meet the deadline for their new collection launch successfully and without any complications.`}
                        
                    />
                </div>
                <div className="rounded-[20px]  bg-[url(/img/products/tryit/tryit-4-bg.png)] bg-cover bg-center bg-no-repeat overflow-hidden mb-[40px] lg:mb-[169px]">
                    <BigImageStory
                        imgUrl={`/img/products/tryit/tryit-4.png`}
                        imageContainerClassname="aspect-[92/44] m-auto max-w-[1440px] mb-[160px]"
                       
                    />
                </div>

                <div className="rounded-[20px] mt-[120px] lg:mt-[200px] pb-20 px-[19px] lg:px-40 lg:pb-[60px] ">
                    <BigImageOnly
                        imgUrl={`/img/products/tryit/tryit-5.png`}
                        className="aspect-[58/53] md:aspect-[52/59] h-full m-auto max-w-[1440px]"
                    />
                </div>
                <BigImageStory
                        title={`Approach`}
                        story={`Shortly after we launched, they were in need of another site for their mix series, Try It Records. We took the initiative and built a continuous playing experience while navigating through the site.`}
                        textColor={`text-white`}
                        textContainerClassname="px-[9px] lg:px-[19px] pb-[160px]"

                    />
            </div>
        </>
    );
}
