"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigImageStory2 from "@/components/sections/big-img-story-2";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import { projectsData } from "../../sections/projectdata";

export default function VicisPage() {
    const project = projectsData.find((project) => project.title === "Vicis");

     if (!project) {
         return <div>Project data not found.</div>;
     }
    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title="VICIS"
                    subtitle="Game-Changing Helmet Technology"
                    desktopImgUrl="/img/products/vicisproduct.png"
                    mobileImgUrl="/img/products/mobile/vicisproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[210px]">
                    <BigTitleStory
                        title={`Football’s most protective helmets for athletes at all ages and levels of competition`}
                        titleLeft={`Services`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter(service => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="VICIS produces advanced football helmets designed to enhance player safety through innovative technology and materials. After being acquired by Certor, they approached us with a request to create a unified shopping experience across their range of brands. "
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-video "
                        imgUrl={`/img/products/vicis/vicis-1.png`}
                        width={`90%`}
                        height={`60%`}
                        title="Approach"
                        story="The objective was to enable users to add products from any of Certor's brand stores and view them in a single shopping cart for a seamless checkout process. This approach aimed to enhance user convenience and streamline the shopping journey."
                    />
                </div>
                <div className="px-[9px] lg:px-[19px]">
                    <BigImageStory2
                        imgUrl={`/img/products/vicis/vicis-2.png`}
                        imageContainerClassname="aspect-[19/18] max-w-[1280px] m-auto md:mb-[120px]"
                        title={`Approach`}
                        story={`With a clear understanding of the prerequisites and a keen awareness of API capabilities and limitations of Shopify Plus, we embarked on the creation of a bespoke app designed to fit seamlessly into this collaborative shopping concept.`}
                        textColor={`text-white`}
                    />
                </div>

                <div className="bg-[#FDFCF3] px-[9px] lg:px-[19px]">
                    <BigImageStory2
                        imgUrl={`/img/products/vicis/vicis-3.png`}
                        imageContainerClassname="aspect-[40/41] max-w-[1280px] m-auto md:mb-[120px] "
                        title={`Approach`}
                        story={`Each brand's store operates through its individual Shopify instance, displaying the custom themes we developed in partnership with MUTO.`}
                    />
                </div>
                <div className="">
                    <BigImageStory2
                        imgUrl={`/img/products/vicis/vicis-4.png`}
                        imageContainerClassname="aspect-[16/9] m-auto md:mb-[120px]"
                        title={`Approach`}
                        story={`The synchronization of cart drawers across all sites ensures a consistent shopping experience, leading to a unified checkout process.`}
                        textColor={`text-white`}
                        textContainerClassname="px-[9px] lg:px-[19px]"
                    />
                </div>
                <div className="bg-[#FDFCF3] px-[9px] lg:px-[19px]">
                    <BigImageStory2
                        imgUrl={`/img/products/vicis/vicis-5.png`}
                        imageContainerClassname="aspect-video max-w-[1280px] m-auto md:mb-[120px]"
                        title={`Vicis`}
                        story={`The synchronization of cart drawers across all sites ensures a consistent shopping experience, leading to a unified checkout process.`}
                    />
                </div>
                <div className="rounded-[20px] mt-[180px] pb-[180px]">
                    <BigImageOnly
                        imgUrl={`/img/products/vicis/vicis-6.png`}
                        contain
                    />
                </div>
            </div>
        </>
    );
}
