"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageSliderStory from "@/components/sections/big-img-slider-story";
import BigImageStory from "@/components/sections/big-img-story";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import { projectsData } from "../../sections/projectdata";

export default function VicisPage() {
    const scrollContainerRef = useRef<HTMLDivElement>(null);
    const speedFactor = 2; // Adjust this value to increase or decrease the scroll speed

    useEffect(() => {
        let isScrolling = false;

        const handleScroll = () => {
            if (scrollContainerRef.current && !isScrolling) {
                isScrolling = true;
                requestAnimationFrame(() => {
                    const rect =
                        scrollContainerRef.current!.getBoundingClientRect();
                    const containerOffsetTop = rect.top + window.pageYOffset;
                    const containerHeight = rect.height;

                    const scrollY = window.pageYOffset;
                    const windowHeight = window.innerHeight;

                    if (
                        scrollY + windowHeight > containerOffsetTop &&
                        scrollY < containerOffsetTop + containerHeight
                    ) {
                        // The section is in view
                        const progress =
                            (scrollY -
                                500 +
                                windowHeight -
                                containerOffsetTop) /
                            (windowHeight + containerHeight);

                        const scrollPercentage = Math.max(
                            0,
                            Math.min(1, progress)
                        );

                        const maxScroll =
                            scrollContainerRef?.current?.scrollWidth! -
                            scrollContainerRef?.current?.clientWidth!;

                        const scrollLeft =
                            maxScroll * scrollPercentage * speedFactor;

                        scrollContainerRef.current!.scrollLeft = Math.max(
                            0,
                            Math.min(maxScroll, scrollLeft)
                        );
                    }
                    isScrolling = false;
                });
            }
        };

        const observerCallback = (entries: IntersectionObserverEntry[]) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    // Start listening to scroll events
                    window.addEventListener("scroll", handleScroll);
                } else {
                    // Stop listening to scroll events
                    window.removeEventListener("scroll", handleScroll);
                }
            });
        };

        const observerOptions = {
            root: null, // Use the viewport as the root
            threshold: 0.5, // Trigger when even one pixel is visible
        };

        const observer = new IntersectionObserver(
            observerCallback,
            observerOptions
        );

        if (scrollContainerRef.current) {
            observer.observe(scrollContainerRef.current);
        }

        // Cleanup on unmount
        return () => {
            observer.disconnect();
            window.removeEventListener("scroll", handleScroll);
        };
    }, []);
    const project = projectsData.find((project) => project.title === "Vicis");

    if (!project) {
        return <div>Project data not found.</div>;
    }
    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title="Vicis"
                    subtitle="Game-Changing Helmet Technology"
                    desktopImgUrl="/img/products/vicisproduct.png"
                    mobileImgUrl="/img/products/mobile/vicisproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[120px]">
                    <BigTitleStory
                        title={`Football’s most protective helmets for athletes at all ages and levels of                 competition`}
                        titleLeft={`Services`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter((service) => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="VICIS produces advanced football helmets designed to enhance player safety through innovative technology and materials. After being acquired by Certor, they approached us with a request to create a unified shopping experience across their range of brands. "
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-video "
                        imgUrl={`/img/products/vicis/vicis-1.png`}
                        width={`90%`}
                        height={`60%`}
                        title="Approach"
                        story="The objective was to enable users to add products from any of Certor's brand stores and view them in a single shopping cart for a seamless checkout process. This approach aimed to enhance user convenience and streamline the shopping journey."
                    />
                </div>
                <div className="rounded-[20px] bg-[#D6D8CE] px-[9px] lg:px-[19px] pb-[120px]">
                    <BigImageStory
                        imgUrl={`/img/products/vicis/vicis-2.png`}
                        imageContainerClassname="aspect-[19/18] max-w-[1280px] m-auto md:mb-[120px]"
                        title={`Approach`}
                        story={`With a clear understanding of the prerequisites and a keen awareness of API capabilities and limitations of Shopify Plus, we embarked on the creation of a bespoke app designed to fit seamlessly into this collaborative shopping concept.`}
                    />
                </div>

                <div className="px-[9px] lg:px-[19px] pb-[120px]">
                    <BigImageStory
                        imgUrl={`/img/products/vicis/vicis-3.png`}
                        imageContainerClassname="aspect-[40/41] max-w-[1280px] m-auto md:mb-[120px] "
                        title={`Approach`}
                        story={`Each brand's store operates through its individual Shopify instance, displaying the custom themes we developed in partnership with MUTO.`}
                        textColor={`text-white`}
                    />
                </div>

                <div className=" flex-col hidden lg:flex relative  mb-[40px] lg:mb-[169px]">
                    <div
                        ref={scrollContainerRef}
                        className="overflow-x-auto  mt-[80px] lg:mt-[169px] no-scrollbar"
                    >
                        <div className="relative min-w-[1988px] aspect-[1988/656]">
                            <Image
                                src={"/img/products/vicis/vicis-4.png"}
                                alt="vicis-4"
                                className="object-contain"
                                fill
                                draggable={false}
                                quality={100}
                                priority
                                unoptimized
                            />
                        </div>
                    </div>
                </div>
                <div className="rounded-[20px] px-[9px] lg:px-[19px] pb-[120px]">
                    <BigImageSliderStory
                        images={[
                            "/img/products/vicis/vicis-5.png",
                            "/img/products/vicis/vicis-7.png",
                            "/img/products/vicis/vicis-8.png",
                        ]}
                        title="Vicis"
                        story={`The synchronization of cart drawers across all sites ensures a consistent shopping experience, leading to a unified checkout process.`}
                        textColor={`text-white`}
                        imageContainerClassname="aspect-video max-w-[1280px] m-auto md:mb-[120px]"
                    />
                </div>
            </div>
        </>
    );
}
