"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigImageStory2 from "@/components/sections/big-img-story-2";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";

export default function VicisPage() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative bg-black">
        <HeroTitle
          title="VICIS"
          subtitle="Game-Changing Helmet Technology"
          desktopImgUrl="/img/products/vicisproduct.png"
          mobileImgUrl="/img/products/mobile/vicisproduct-mobile.png"
        />
        <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono]">
          <BigTitleStory
            title={`Football’s most protective helmets for athletes at all ages and levels of competition`}
            titleLeft={`Schutt`}
            textRight="VICIS produces advanced football helmets designed to enhance player safety through innovative technology and materials. After being acquired by Certor, they approached us with a request to create a unified shopping experience across their range of brands. "
          />

          <BigImageStory
            imageClassname="aspect-square md:aspect-video lg:mb-16 "
            imgUrl={`/img/products/vicis/vicis-1.png`}
            width={`90%`}
            height={`60%`}
            title="Approach"
            story="The objective was to enable users to add products from any of Certor's brand stores and view them in a single shopping cart for a seamless checkout process. This approach aimed to enhance user convenience and streamline the shopping journey."
          />
        </div>
        <div className="">
          <BigImageStory2
            imgUrl={`/img/products/vicis/vicis-2.png`}
            imageClassname="aspect-[19/18] max-w-[1196px] m-auto"
            title={`Approach`}
            story={`With a clear understanding of the prerequisites and a keen awareness of API capabilities and limitations of Shopify Plus, we embarked on the creation of a bespoke app designed to fit seamlessly into this collaborative shopping concept.`}
            textColor={`text-white`}
          />
        </div>

        <div className="bg-[#FDFCF3] ">
          <BigImageStory2
            imgUrl={`/img/products/vicis/vicis-3.png`}
            imageClassname="aspect-[40/41]  m-auto"
            title={`Approach`}
            story={`Each brand's store operates through its individual Shopify instance, displaying the custom themes we developed in partnership with MUTO.`}
          />
        </div>
        <div className="">
          <BigImageStory2
            imgUrl={`/img/products/vicis/vicis-4.png`}
            imageClassname="aspect-[20/9] m-auto"
            title={`Approach`}
            story={`The synchronization of cart drawers across all sites ensures a consistent shopping experience, leading to a unified checkout process.`}
            textColor={`text-white`}
          />
        </div>
        <div className="bg-[#FDFCF3] ">
          <BigImageStory2
            imgUrl={`/img/products/vicis/vicis-5.png`}
            imageClassname="aspect-video  m-auto"
            title={`Vicis`}
            story={`Vicis is a sports equipment company that specializes in developing advanced football helmets designed to reduce the risk of head injuries for players.`}
            story2={`The company uses innovative technology and materials to create helmets that are both effective and comfortable to wear, with a focus on improving the safety of the sport.`}
            story3={` Vicis has gained recognition and partnerships with numerous NFL teams and players, as well as being awarded grants from the NFL Players Association and the US Department of Defense.`}
          />
        </div>
        <div className="rounded-[20px] mt-10">
          <BigImageOnly imgUrl={`/img/products/vicis/vicis-6.png`} contain/>
        </div>
      </div>
    </>
  );
}
