"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import { projectsData } from "../../sections/projectdata";
import BigImageStory2 from "@/components/sections/big-img-story-2";

export default function VoltAthleticsPage() {
    const scrollContainerRef = useRef<HTMLDivElement>(null);
    const speedFactor = 2; // Adjust this value to increase or decrease the scroll speed

    useEffect(() => {
        let isScrolling = false;

        const handleScroll = () => {
            if (scrollContainerRef.current && !isScrolling) {
                isScrolling = true;
                requestAnimationFrame(() => {
                    const rect =
                        scrollContainerRef.current!.getBoundingClientRect();
                    const containerOffsetTop = rect.top + window.pageYOffset;
                    const containerHeight = rect.height;

                    const scrollY = window.pageYOffset;
                    const windowHeight = window.innerHeight;

                    if (
                        scrollY + windowHeight > containerOffsetTop &&
                        scrollY < containerOffsetTop + containerHeight
                    ) {
                        // The section is in view
                        const progress =
                            (scrollY -500 +windowHeight - containerOffsetTop) /
                            (windowHeight + containerHeight);

                        const scrollPercentage = Math.max(
                            0,
                            Math.min(1, progress)
                        );

                        const maxScroll =
                            scrollContainerRef?.current?.scrollWidth! -
                            scrollContainerRef?.current?.clientWidth!;

                        const scrollLeft =
                            maxScroll * scrollPercentage * speedFactor;

                        scrollContainerRef.current!.scrollLeft = Math.max(
                            0,
                            Math.min(maxScroll, scrollLeft)
                        );
                    }
                    isScrolling = false;
                });
            }
        };

        const observerCallback = (entries: IntersectionObserverEntry[]) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    // Start listening to scroll events
                    window.addEventListener("scroll", handleScroll);
                } else {
                    // Stop listening to scroll events
                    window.removeEventListener("scroll", handleScroll);
                }
            });
        };

        const observerOptions = {
            root: null, // Use the viewport as the root
            threshold: 0.5, // Trigger when even one pixel is visible
        };

        const observer = new IntersectionObserver(
            observerCallback,
            observerOptions
        );

        if (scrollContainerRef.current) {
            observer.observe(scrollContainerRef.current);
        }

        // Cleanup on unmount
        return () => {
            observer.disconnect();
            window.removeEventListener("scroll", handleScroll);
        };
    }, []);
    const project = projectsData.find(
        (project) => project.title === "Volt Athletics"
    );

    if (!project) {
        return <div>Project data not found.</div>;
    }

    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title="Volt Athletics"
                    subtitle="Maximize Your Coaching Impact"
                    desktopImgUrl="/img/products/voltproduct.png"
                    mobileImgUrl="/img/products/mobile/voltproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[120px]">
                    <BigTitleStory
                        title={`Expert fitness guidance, whether you are training as an individual or part of a group`}
                        titleLeft={`Services`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter((service) => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="Volt Athletics specializes in providing strength and conditioning solutions for athletes. Their training app combines cutting-edge technology with expert coaching to create individualized training plans that cater to each athlete's goals and needs."
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-video  "
                        imgUrl={"/img/products/volt/volt-1.png"}
                        width={`90%`}
                        height={`60%`}
                        title={`Challenge`}
                        story={`As Volt Athletics was undertaking a digital revamp, we were brought in to seamlessly blend design and functionality to enhance Volt Athletics' online presence. This required creating a high-performing front-end that prioritized speed, SEO, and accessibility while still aligning with the website's redesign.  `}
                    />
                </div>
                <div className="bg-[#D6D8CE] rounded-[20px] pb-[120px]">
                    <BigImageStory
                        imageClassname=" px-[9px] lg:px-[19px]"
                        imgUrl={"/img/products/volt/volt-2.png"}
                        imageContainerClassname="aspect-[92/59] max-w-[1440px] m-auto md:mb-[120px]"
                        title={`Approach`}
                        textContainerClassname="px-[9px] lg:px-[19px]"
                        story={`Following our initial discussions with the Volt team, a mutual decision was made to employ a more modern react-based framework for their front-end.`}
                    />
                </div>
                <div className=" flex-col hidden lg:flex relative  mb-[40px] lg:mb-[169px]">
                    <div
                        ref={scrollContainerRef}
                        className="overflow-x-auto  mt-[80px] lg:mt-[169px] no-scrollbar"
                    >
                        <div className="relative h-[538px] w-[3588px]">
                            <Image
                                src={"/img/products/volt/volt-3.png"}
                                alt="volt-3"
                                className="object-contain"
                                fill
                                draggable={false}
                                quality={100}
                                priority
                                unoptimized
                            />
                        </div>
                    </div>
                    <BigImageStory
                        title={`Approach`}
                        story={`The development process was segmented into phases, aligning with app releases. Upon receiving approved designs, we diligently constructed each new page as they were delivered. `}
                        textColor={`text-white`}
                        textContainerClassname="px-[9px] lg:px-[19px] mt-[80px] lg:mt-[169px] pb-[120px]"
                    />
                </div>
                <div className="bg-[#FDFCF3] lg:hidden pb-[120px]">
                    <BigImageStory
                        imgUrl={"/img/products/volt/volt-3.png"}
                        imageContainerClassname="aspect-[45/7] m-auto h-full w-full lg:hidden"
                        textContainerClassname="px-[9px] lg:px-[19px] "
                        title={`Approach`}
                        story={`Post comprehensive quality assurance conducted by all stakeholders, necessary modifications were implemented before launching the new website, meeting all requirements and expectations. `}
                    />
                </div>
                <div className="rounded-[20px] bg-[#FDFCF3] pb-20  lg:pb-[120px] ">
                    <BigImageStory2
                        imageClassname=" px-[9px] lg:px-[19px]"
                        imgUrl={"/img/products/volt/volt-5.png"}
                        imageContainerClassname="aspect-[92/59] m-auto md:mb-[120px]"
                        title={`Approach`}
                        story={`Post comprehensive quality assurance conducted by all stakeholders, necessary modifications were implemented before launching the new website, meeting all requirements and expectations. `}
                        textContainerClassname="px-[9px] lg:px-[19px]"
                    />
                </div>
                <div className="rounded-[20px] overflow-hidden">
                    <BigImageOnly
                            imgUrl={"/img/products/volt/volt-4.png"}
                            imageClassname=" lg:object-cover"
                            className="aspect-[16/9] m-auto"
                        />
                </div>
            </div>
        </>
    );
}
