"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigImageStory2 from "@/components/sections/big-img-story-2";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { projectsData } from "../../sections/projectdata";

export default function VoltAthleticsPage() {
    const project = projectsData.find((project) => project.title === "Volt Athletics");
    const scrollContainerRef = useRef<HTMLDivElement>(null);
    const [isDragging, setIsDragging] = useState(false);
    const [startX, setStartX] = useState(0);
    const [scrollLeft, setScrollLeft] = useState(0);

    const handleMouseDown = (e: React.MouseEvent) => {
        setIsDragging(true);
        setStartX(e.pageX - scrollContainerRef.current!.offsetLeft);
        setScrollLeft(scrollContainerRef.current!.scrollLeft);
    };

    const handleMouseUp = () => {
        setIsDragging(false);
    };

    const handleMouseMove = (e: React.MouseEvent) => {
        if (!isDragging) return;
        e.preventDefault();
        const x = e.pageX - scrollContainerRef.current!.offsetLeft;
        const walk = (x - startX) * 2; // Adjust scrolling speed
        scrollContainerRef.current!.scrollLeft = scrollLeft - walk;
    };

    useEffect(() => {
        document.addEventListener("mouseup", handleMouseUp);
        return () => document.removeEventListener("mouseup", handleMouseUp);
    }, []);

     if (!project) {
         return <div>Project data not found.</div>;
     }
    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-dark">
                <HeroTitle
                    title="VOLT ATHLETICS"
                    subtitle="Maximize Your Coaching Impact"
                    desktopImgUrl="/img/products/voltproduct.png"
                    mobileImgUrl="/img/products/mobile/voltproduct-mobile.png"
                />
                <div className="bg-[#FDFCF3] rounded-[20px] font-[MonumentGrotesk-Semi-Mono] px-[9px] lg:px-[19px] pb-[80px] lg:pb-[210px]">
                    <BigTitleStory
                        title={`Expert fitness guidance, whether you are training as an individual or part of a group`}
                        titleLeft={`Services`}
                        textLeft={
                            <ul>
                                {project.services
                                    .filter(service => service) // Filter out empty strings
                                    .map((service, index) => (
                                        <li key={index}>{service}</li>
                                    ))}
                            </ul>
                        }
                        titleRight={`About`}
                        textRight="Volt Athletics specializes in providing strength and conditioning solutions for athletes. Their training app combines cutting-edge technology with expert coaching to create individualized training plans that cater to each athlete's goals and needs."
                    />

                    <BigImageStory
                        imageContainerClassname="aspect-square md:aspect-video  "
                        imgUrl={"/img/products/volt/volt-1.png"}
                        width={`90%`}
                        height={`60%`}
                        title={`Challenge`}
                        story={`As Volt Athletics was undertaking a digital revamp, we were brought in to seamlessly blend design and functionality to enhance Volt Athletics' online presence. This required creating a high-performing front-end that prioritized speed, SEO, and accessibility while still aligning with the website's redesign.  `}
                    />
                </div>
                <div className="bg-[#D6D8CE] rounded-[20px]">
                    <BigImageStory2
                        imageClassname=" px-[9px] lg:px-[19px]"
                        imgUrl={"/img/products/volt/volt-2.png"}
                        imageContainerClassname="aspect-[92/59] max-w-[1440px] m-auto md:mb-[120px]"
                        title={`Approach`}
                        textContainerClassname="px-[9px] lg:px-[19px]"
                        story={`Following our initial discussions with the Volt team, a mutual decision was made to employ a more modern react-based framework for their front-end.`}
                    />
                </div>
                <div className="translate-y-10 flex-col hidden lg:flex relative">
                    <div
                        className="overflow-x-auto  mt-[80px] lg:mt-[169px] no-scrollbar"
                        onMouseDown={handleMouseDown}
                        ref={scrollContainerRef}
                        onMouseMove={handleMouseMove}
                    >
                        <div className="relative h-[538px] w-[3588px]">
                            <Image
                                src={"/img/products/volt/volt-3.png"}
                                alt="volt-3"
                                className="object-contain"
                                fill
                                draggable={false}
                                quality={100}
                                priority
                                unoptimized
                            />
                        </div>
                    </div>
                    <BigImageStory2
                        title={`Approach`}
                        story={`Following our initial discussions with the Volt team, a mutual decision was made to employ a more modern react-based framework for their front-end.`}
                        textColor={`text-white`}
                        textContainerClassname="px-[9px] lg:px-[19px] mt-[80px] lg:mt-[169px] "
                    />
                </div>
                <div className="bg-[#FDFCF3] lg:hidden">
                    <BigImageStory2
                        imgUrl={"/img/products/volt/volt-3.png"}
                        imageContainerClassname="aspect-[45/7] m-auto h-full w-full lg:hidden"
                        textContainerClassname="px-[9px] lg:px-[19px] "
                        title={`Approach`}
                        story={`Following our initial discussions with the Volt team, a mutual decision was made to employ a more modern react-based framework for their front-end.`}
                    />
                </div>
                <div className="bg-[#FDFCF3] rounded-[20px]">
                    <BigImageStory2
                        imageClassname=" px-[9px] lg:px-[19px]"
                        imgUrl={"/img/products/volt/volt-4.png"}
                        imageContainerClassname="aspect-[92/59] m-auto md:mb-[120px]"
                        title={`Approach`}
                        story={`Post comprehensive quality assurance conducted by all stakeholders, necessary modifications were implemented before launching the new website, meeting all requirements and expectations. `}
                        textContainerClassname="px-[9px] lg:px-[19px]"
                    />
                </div>
                <div className="rounded-[20px] mt-[120px] lg:mt-[200px] pb-20 lg:px-40 lg:pb-[200px] ">
                    <BigImageOnly
                        imgUrl={"/img/products/volt/volt-5.png"}
                        imageClassname=" lg:object-contain"
                        className="aspect-[41/42]"
                    />
                </div>
            </div>
        </>
    );
}
