import Footer from "@/components/layout/footer";
import NewHeader from "@/components/layout/new-header";
import type { Metadata } from "next";
import "swiper/css";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="max-w-full m-auto">
                <NewHeader />
                {children}
                <Footer />
            </body>
        </html>
    );
}
