"use client";
import HeroTitle from "@/components/common/HeroTitle";
import BigImageOnly from "@/components/sections/big-img-only";
import BigImageStory from "@/components/sections/big-img-story";
import BigImageStory2 from "@/components/sections/big-img-story-2";
import BigTitleStory from "@/components/sections/big-title-story";
import Head from "next/head";

export default function CasesPage() {
    return (
        <>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="relative bg-black">
                <HeroTitle title="SPEAKEASY" subtitle="Spirits Brands' Best Friend" />
                <div className="bg-white rounded-[20px]">
                    <BigTitleStory 
                        title={`INTEGRATED 
                            DIRECT-TO-CONSUMER 
                            SOLUTIONS FOR BEVERAGE 
                            ALCOHOL BRANDS`}
                        titleLeft={`Services`}
                        textLeft={`1. UX/UI DESIGN
                            2. CUSTOM THEME DEVELOPMENT
                            3. STORE SET-UP
                            4. APP INTEGRATION
                            5. CUSTOM APP DEVELOPMENT`}
                        titleRight={`About`}
                        textRight="Speakeasy Co. offers a complete solution for beverage alcohol brands, including technology, warehousing, and order fulfillment. We joined forces with Speakeasy Co. as they sought a modern eCommerce solution for their clients."/>

                    <BigImageStory
                        imgUrl={`/img/new-layout/item-1.png`}
                        width={`90%`}
                        height={`60%`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands. `}
                    />
                </div>

                <div className="bg-[#D6D8CE] rounded-[20px]">
                    <BigImageStory
                        imgUrl={`/img/new-layout/item-2.png`}
                        width={`65%`}
                        height={`100%`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands. `}
                    />
                </div>

                <div className="">
                    <BigImageStory2
                        imgUrl={`/img/new-layout/item-3.png`}
                        width={`1196px`}
                        height={`1360px`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands. `}
                        textColor={`text-white`}
                    />
                </div>

                <div className="bg-[#D6D8CE] rounded-[20px]">
                    <BigImageStory2
                        imgUrl={`/img/new-layout/item-4.png`}
                        width={`1196px`}
                        height={`1360px`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands. `}
                    />
                </div>

                <div className="">
                    <BigImageStory2
                        imgUrl={`/img/new-layout/item-5.png`}
                        width={`1000px`}
                        height={`1280px`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands. `}
                        textColor={`text-white`}
                    />
                </div>

                <div className="bg-[#D6D8CE] rounded-[20px]">
                    <BigImageStory2
                        imgUrl={`/img/new-layout/item-6.png`}
                        width={`75%`}
                        height={`100%`}
                        title={`Challenge`}
                        story={`The goal was to migrate client stores from outdated Magento front-ends to Shopify. Our expertise in Shopify development made us the perfect candidate to support Speakeasy and their client brands. `}
                    />
                </div>
                <div className="rounded-[20px]">
                    <BigImageOnly
                        imgUrl={`/img/new-layout/item-7.png`}
                    />
                </div>
            </div>
        </>
    );
}