"use client";
import HeroSlideShow from "@/components/common/HeroSlideshow";
import Head from "next/head";
import ProjectList from "../sections/project-list";

export default function Homepage() {
    
    return (
        <>
            <Head>
                <title>Studio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           
            <div className="relative bg-black">
            <HeroSlideShow/>
            <ProjectList/>
            </div>
       
        
        </>
    );
}
